[toolchain]
anchor_version = "0.31.1"

[features]
seeds = false
skip-lint = false
default = []
testing = []

[programs.localnet]
launchpad_program = "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS"

[programs.devnet]
launchpad_program = "5dhQapnBy7pXnuPR9fTbgvFt4SsZCWiwQ4qtMEVSMDvZ"

[registry]
url = "https://api.apr.dev"

[provider]
# cluster = "devnet"
cluster = "https://devnet.helius-rpc.com/?api-key=62d4baa9-f668-4311-a736-b21fea80169e"
wallet = "programs/launchpad-program/.launchpad_admin.privkey"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[build]
arch = "sbf"
idl = "types"

[workspace]
types = "types"

[[test.genesis]]
address = "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS"
program = "target/deploy/launchpad_program.so" 
